# Sailfin compiler Conda environment
name: sailfin
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - ply>=3.11,<4.0
  - pyinstaller>=6.11.1,<7.0.0
  - pip:
      - python-semantic-release>=9.17.0,<10.0.0
