export enum RequestHeader {
  ACCEPT = 'accept',
  CONTENT_TYPE = 'content-type',
  AUTHORIZATION = 'authorization',
  USER_AGENT = 'user-agent',
  HOST = 'host',
  REFERRER = 'referrer',
  COOKIE = 'cookie',
  SET_COOKIE = 'set-cookie',
  LOCATION = 'location',
  ORIGIN = 'origin',
  X_FORWARDED_FOR = 'x-forwarded-for',
  X_FORWARDED_HOST = 'x-forwarded-host',
  X_FORWARDED_PROTO = 'x-forwarded-proto',
  X_REQUESTED_WITH = 'x-requested-with',
  X_CSRF_TOKEN = 'x-csrf-token',
  X_XSRF_TOKEN = 'x-xsrf-token',
  X_HTTP_METHOD_OVERRIDE = 'x-http-method-override',
  X_POWERED_BY = 'x-powered-by',
  X_REAL_IP = 'x-real-ip',
  X_REQUEST_ID = 'x-request-id',
}
